CREATE TABLE IF NOT EXISTS problems(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    title VARCHAR(255) NOT NULL,
    problem_subject TEXT NOT NULL,
    email TEXT NOT NULL,
    day_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)